/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.javascool.proglets.jeux2D;


import java.applet.Applet;
import java.awt.Color;
import java.util.logging.Logger;
import javax.swing.JApplet;

/**
 *
 * @author gmatheron
 */
public class Panel extends JApplet {

    private static final long serialVersionUID = 1L;
    private static final Logger LOG = Logger.getLogger(Panel.class.getName());
    private GamePanel m_panel;
    
    public Panel() {
        m_panel=new GamePanel();
        setContentPane(m_panel);
    }
    
    public GamePanel getGamePanel() {
        return m_panel;
    }
    
    @Override
    public void init() {
        PrivateFunctions.start();
    }
    
    @Override
    public void destroy() {
        PrivateFunctions.stop();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
