<!DOCTYPE html>
<html lang="fr">
<head>
  <title>Bienvenue sur «BAHHZ»</title>
  <meta charset="UTF-8">
  <style type="text/css">
      #main { margin-top: 80px;  }
  </style>
  <link href="./assets/pygments.css" rel="stylesheet">
  <link href="./assets/bootstrap/css/bootstrap.css" rel="stylesheet">
  <link href="./assets/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
</head><body style="background-color:#FFFFFF;">
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="./index.html" style="margin: 0; margin-right: 30px; margin-top: 3px; padding:0;">
        <img alt="logo" src="./logo-original.jpg" style="height: 35px; padding: 0; margin: 0;"/>&nbsp;<b>Java'sCool 5</b> 
      </a>
      <div class="nav-collapse">
        <ul class="nav">
          <li class="active"><a href="./notrejeu.htm">Lancer le jeu</a></li>
          <li><a href="./apropos.htm">À propos du jeu</a></li>
          <li><a href="./notrejeu.zip">Les fichiers source</a></li>
          <li><a href="./credits.htm">Crédits</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="container" id="main">

