
ANDROID=/usr/java/android-sdk/tools/android

# Starts the android emulator interface

avd:
	$(ANDROID) avd &

# Compiles and install the package on android

cmp:
	ant installd

# This is the command used to create this bundle
## /usr/java/android-sdk/tools/android create project --package org.javascool.proglets.helloAndroid --activity HelloAndroid --target 1 --path /home/vthierry/Work/culsci/jvs/sketchbook/helloAndroid
