all :
	javac *.java
	rm -f grafikformate.jar; jar cf grafikformate.jar *.class ; rm -f *.class
	appletviewer grafikformate.html


#cnv :
#	for f in *.java ; do mv $$f $$f.save ; iconv -f ISO8859-1 -t UTF-8 $$f.save > $$f ; done

