# vthierry's commands et tbd
### http://code.google.com/p/javascool/wiki/JavaScoolOnGoingWork & http://code.google.com/p/javascool/issues/list

# Using sun-jdk because of processing and windows platforms
export JHOME=/usr/java/jdk1.6.0_22
export PATH:=$(JHOME)/bin:$(PATH)

ant : 
	ant prun

nbe :
	netbeans --jdkhome $(JHOME) &

#
# ProProglets:
#   1. Ajouter les width et height pour les processing + les tailles dans ProgletEngine + test dans Builder
#   3. 4 x Ajouter les completion.xml dans les proglets
#   4. 4 x Mettre a plat les Functions.java
#   5. 4 x tester les programmes exemples
#
# Basculement site
#  virer /home/groups/javascool/htdocs/{index|sketchbook|javascool.jar|sources.zip|index.php}
#  ln -s v4/index.php .
#



